export const SAVE_FUEL_SAVINGS = 'SAVE_FUEL_SAVINGS';
export const CALCULATE_FUEL_SAVINGS = 'CALCULATE_FUEL_SAVINGS';
export const SET_FAVORITE = "SET_FAVORITE";
export const UNSET_FAVORITE = "UNSET_FAVORITE";
